# netlify.toml

[build]
  command   = "pnpm build"
  publish   = "dist"

[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION     = "18"

# Redirect all paths to index.html for client-side routing
[[redirects]]
  from     = "/*"
  to       = "/Login.tsx"
  status   = 200
  force    = true
