# netlify.toml (at the repo root)

[build]
  command   = "pnpm run build"
  publish   = "dist"

[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION     = "18"

# === Single-Page App fallback: serve index.html for all paths ===
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
  force  = true
